_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 50
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-x86_64
experiment_name:
    value: default_experiment
model_conf:
    value:
        num_classes: 5
seed:
    value: 42
training_conf:
    value:
        batch_size: 128
        learning_rate: 0.001
        max_images: 20
        num_epochs: 2
        sample_ratio: 0.01
