# environment.yml
# Use this file to create the Conda environment:
# $ conda env create -f environment.yml

name: basic_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0
  - torchvision=0.15
  - tqdm
  - requests
  - pillow
  - omegaconf
  - pip
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - statsmodels
  - matplotlib
  - pytest
  - pytest-cov
  - fastapi
  - uvicorn
  - pytorch_lightning
  - jinja2
  - protobuf
  - pydantic
  - pip:
      - typer
      - hydra-core
      - wandb
      - evidently
      - litestar
      - litestar-htmx
      - rich
      - plotly
      - onnxruntime
      - python-dotenv
