# configs/sweep_config.yaml
method: bayes
metric:
  name: epoch_accuracy
  goal: maximize
parameters:
  learning_rate:
    distribution: log_uniform
    min: -10.0
    max: -2.0
  batch_size:
    values: [32, 64, 128]
  num_epochs:
    values: [10, 20, 30]
  max_images:  # Add this if you want to sweep over this parameter
    values: [100, 200, 300]  # Example values