name: Data Change Workflow

on:
  push:
    paths:
      - '**/*.dvc'
      - '.dvc/config'
      - '.dvcignore'

jobs:
  check-data-change:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DVC
        run: pip install dvc

      - name: Verify Data Integrity
        run: dvc status
