name: Model Registry and Code Workflow

on:
  push:
    paths:
      - 'models/**'        # Triggers on changes to the models folder
      - 'src/rice/model.py'  # Triggers on changes to model.py

jobs:
  check-model-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Model Changes
        run: |
          echo "Changes detected in model registry or model code"
          ls models/ || echo "No changes in models folder"
          cat src/rice/model.py || echo "No changes in model.py"
